import io
import os
import re
import sys

# Make rlPyCairo use pycairo (its bundled cairo works on Windows) instead of cairocffi
sys.modules['cairocffi'] = None

from svglib.svglib import svg2rlg
from reportlab.graphics import renderPM
from graphviz import Digraph

script_dir = os.path.dirname(os.path.abspath(__file__))
png_dir = os.path.join(script_dir, 'icons_png')   # keep generated PNGs out of the way
os.makedirs(png_dir, exist_ok=True)


def svg_to_png(svg_name, dpi=150):
    """Convert an icon SVG to PNG and return its absolute path (forward slashes for Graphviz)."""
    svg_path = os.path.join(script_dir, svg_name)

    with open(svg_path, encoding='utf-8') as f:
        svg_text = f.read()

    if 'Generated by graphviz' in svg_text[:500]:
        raise ValueError(
            f"'{svg_name}' is a Graphviz diagram, not a device icon. "
            "Replace it with the original icon SVG (e.g. re-export it from draw.io)."
        )

    # draw.io uses CSS colours svglib can't read, so parts of the icon go missing.
    # var(--name, fallback) -> fallback
    svg_text = re.sub(r'var\(\s*--[\w-]+\s*,\s*((?:[^()]|\((?:[^()]|\([^()]*\))*\))+?)\s*\)',
                      r'\1', svg_text)
    # light-dark(<light>, <dark>) -> light-mode colour
    svg_text = re.sub(r'light-dark\(\s*((?:rgb\([^)]*\))|[^,()]+)\s*,\s*(?:(?:rgb\([^)]*\))|[^,()]+)\s*\)',
                      r'\1', svg_text)

    png_path = os.path.join(png_dir, svg_name.replace('.svg', '.png'))
    drawing = svg2rlg(io.BytesIO(svg_text.encode('utf-8')))
    renderPM.drawToFile(drawing, png_path, fmt='PNG', dpi=dpi)
    return png_path.replace('\\', '/')


def icon_node(dot, node_id, text, png_path):
    """A node that shows the icon with the caption underneath (no ellipse, no text over the icon)."""
    label = (
        '<<TABLE BORDER="0" CELLBORDER="0" CELLSPACING="0">'
        f'<TR><TD><IMG SRC="{png_path}"/></TD></TR>'
        f'<TR><TD><FONT POINT-SIZE="12">{text}</FONT></TD></TR>'
        '</TABLE>>'
    )
    dot.node(node_id, label=label, shape='none', margin='0')


dd_png = svg_to_png('Distributed Center.svg')
wd_png = svg_to_png('Workgroup.svg')

dot = Digraph('network_diagram', format='png')
dot.attr(rankdir='LR')
dot.attr('node', fontname='Arial')

icon_node(dot, 'DD', 'Distributed Director', dd_png)
dot.node('S1', 'Switch 1', shape='box', style='rounded')
dot.node('S2', 'Switch 2', shape='box', style='rounded')

icon_node(dot, 'WD', 'Workgroup Director', wd_png)
dot.node('PC1', 'PC 1', shape='box', style='rounded')
dot.node('PC2', 'PC 2', shape='box', style='rounded')

dot.edge('DD', 'S1')
dot.edge('DD', 'S2')
dot.edge('WD', 'PC1')
dot.edge('WD', 'PC2')

dot.render(filename='network_diagram', directory=script_dir, cleanup=True)
print('Saved', os.path.join(script_dir, 'network_diagram.png'))