version: "3.9"

services:
  mcpserver:
    build: ./server
    container_name: mcpserver
    ports:
      - "3000:3000"

  hostclient:
    build: ./host_client
    container_name: hostclient
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mcpserver
